package ru.clevertec.checkservlets.dao;

import ru.clevertec.checkservlets.dao.api.CrudDao;
import ru.clevertec.checkservlets.model.Product;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class ProductDao implements CrudDao<Product> {

    private static final String INSERT_INTO_QUERY = "INSERT INTO clevertec_shop.product(name, price, is_promotional) VALUES(?,?,?);";
    private static final String SELECT_BY_ID_QUERY = "SELECT * FROM clevertec_shop.product WHERE id=?;";
    private static final String SELECT_PAGE_QUERY = "SELECT * FROM clevertec_shop.product LIMIT ? OFFSET ?;";
    private static final String SELECT_ALL_QUERY = "SELECT * FROM clevertec_shop.product;";
    private static final String UPDATE_QUERY = "UPDATE clevertec_shop.product SET name=?, price=?, is_promotional=? WHERE id=?;";
    private static final String DELETE_QUERY = "DELETE FROM clevertec_shop.product WHERE id=?;";

    private static ProductDao instance;

    public static ProductDao getInstance() {
        if (instance == null) {
            instance = new ProductDao();
        }
        return instance;
    }

    /**
     * Creates new product in database.<br/>
     * Returns null if something goes wrong.
     *
     * @param entity new product
     * @return id generated by database
     */
    @Override
    public Integer create(Product entity) {
        try (Connection connection = DaoDataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(INSERT_INTO_QUERY,
                     Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, entity.getName());
            ps.setDouble(2, entity.getPrice());
            ps.setBoolean(3, entity.isPromotional());
            ps.executeUpdate();
            ResultSet generatedKeys = ps.getGeneratedKeys();
            if (generatedKeys.next()) {
                return generatedKeys.getInt(1);
            } else {
                throw new SQLException("Id wasn't generated.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Gets product from database by id.
     *
     * @param id id of desired product
     * @return product from database if it exists, null otherwise
     */
    @Override
    public Product read(int id) {
        Product product = null;
        try (Connection connection = DaoDataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(SELECT_BY_ID_QUERY)) {
            ps.setInt(1, id);
            ResultSet resultSet = ps.executeQuery();
            resultSet.next();
            product = new Product(resultSet);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return product;
    }

    /**
     * Gets products from database with pagination. <br/>
     * Might return empty list if something goes wrong.
     *
     * @param page  number of page
     * @param limit limit of fetch
     * @return list of products
     */
    @Override
    public List<Product> readAll(int page, int limit) {
        int offset = (page - 1) * limit;
        List<Product> products = new ArrayList<>();
        try (Connection connection = DaoDataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(SELECT_PAGE_QUERY)) {
            ps.setInt(1, limit);
            ps.setInt(2, offset);
            ResultSet resultSet = ps.executeQuery();
            while (resultSet.next()) {
                products.add(new Product(resultSet));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return products;
    }

    /**
     * Gets all products from database. <br/>
     * Might return empty list if something goes wrong.
     *
     * @return list of products
     */
    @Override
    public List<Product> readAll() {
        List<Product> products = new ArrayList<>();
        try (Connection connection = DaoDataSource.getConnection();
             Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery(SELECT_ALL_QUERY);
            while (resultSet.next()) {
                products.add(new Product(resultSet));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return products;
    }

    /**
     * Updates product in database with id from newEntity. <br/>
     * Returns null if something goes wrong.
     *
     * @param newEntity product to update
     * @return list of products
     */
    @Override
    public Product update(Product newEntity) {
        try (Connection connection = DaoDataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(UPDATE_QUERY)) {
            ps.setString(1, newEntity.getName());
            ps.setDouble(2, newEntity.getPrice());
            ps.setBoolean(3, newEntity.isPromotional());
            ps.setInt(4, newEntity.getId());
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
        return newEntity;
    }

    /**
     * Deletes product from database by id.<br/>
     *
     * @param id id of entity to delete
     */
    @Override
    public void delete(int id) {
        try (Connection connection = DaoDataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(DELETE_QUERY)) {
            ps.setInt(1, id);
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
